FROM pytorch/pytorch:2.1.1-cuda12.1-cudnn8-runtime

RUN apt update -y && \
apt install git -y
RUN pip install ftfy regex tqdm && \
pip install git+https://github.com/openai/CLIP.git
RUN pip install laion-clap
RUN pip install msclap
RUN pip install jupyterlab
RUN pip install matplotlib
RUN mkdir /musicgen && \
cd /musicgen

CMD jupyter lab --allow-root --ip=172.17.02 --no-browser
